### ISSUE TITLE
Feature requests - pop at launch/force to white

### ISSUE THREAD

**Issue by PierreBresson** [adamhartford/PopStatusItem#1]
Hi !

I'm wondering if I can force my app to popup at launch because it's confusing for user who never use any app from the status bar before.
I'm also wondering if I can apply white appareance for dark mode users.

I'm using your pod for a very small class project and it's very helpfull and reliable so far, thanks ;)

**Comment by adamhartford** [comment]
Thanks for the suggestions. See the latest code on the trunk (the demo specifically) for examples of how to do these things now.

The appearance still isn't quite right. I can force Aqua appearance on the popover and button, but the text field is still black. If we can figure that out, I'll publish version 0.4.1 with both of these changes.

**Comment by PierreBresson** [comment]
Thanks for the help , aqua appearance is working well :) 

However I did like in the demo and showing popover on startup code is not working.

<img width="815" alt="screen shot 2015-11-25 at 12 31 57" src="https://cloud.githubusercontent.com/assets/8709134/11408984/c8ac94ee-93b4-11e5-9c79-7df606cc80af.png">

**Comment by adamhartford** [comment]
I haven't published an updated pod yet, so you'll have to point to the trunk:

```
pod 'PopStatusItem', :head
```

Then `pod update`

I will publish the pod later today, though.

**Comment by PierreBresson** [comment]
Now it's working perfectly well, cheers ;)
